Update tg_pxy

diff --git a/tg_pxy b/tg_pxy
--- a/tg_pxy
+++ b/tg_pxy
@@ -1,5 +1,4 @@
 #!/bin/bash
-
 #######设置信息颜色############
 ERROR="31m"      # Error message
 SUCCESS="32m"    # Success message
@@ -26,8 +25,6 @@ bred(){
 byellow(){
     echo -e "\033[33m\033[01m\033[05m$1\033[0m"
 }
-
-apt install curl -y
 
 regex='^[0-9]+$'
 function RemoveMultiLineUser() {
@@ -164,20 +161,22 @@ if [ -d "/opt/mtprotoproxy" ]; then
 			fi
 		fi
 	else
-		echo "You have already installed MTProtoProxy! What do you want to do?"
-		echo "  1 ) View all connection links"
-		echo "  2 ) Upgrade proxy software"
-		echo "  3 ) Change AD TAG"
-		echo "  4 ) Add a secret"
-		echo "  5 ) Revoke a secret"
-		echo "  6 ) Change user connection limits"
-		echo "  7 ) Change user expiry date"
-		echo "  8 ) Change user quota options"
-		echo "  9 ) Generate firewall rules"
-		echo "  10) Uninstall Proxy" 
+    echo ""
+  green " 已成功安装好tg代理"
+  green " 版本：20200304v1"
+  green " ========================================================================"
+		echo "  1 ) 显示在用得tg代理链接"
+		#echo "  2 ) Upgrade proxy software"
+		#echo "  3 ) Change AD TAG"
+		#echo "  4 ) Add a secret"
+		#echo "  5 ) Revoke a secret"
+		#echo "  6 ) Change user connection limits"
+		#echo "  7 ) Change user expiry date"
+		#echo "  8 ) Change user quota options"
+		#echo "  9 ) Generate firewall rules"
+		echo "  10) Uninstall Proxy"
 		echo "  * ) Exit"
-        echo "  * 20200304v3"
-		read -r -p "Please enter a number: " OPTION
+		read -r -p "请选择: " OPTION
 	fi
 	case $OPTION in
 	#View connection links
@@ -550,20 +549,41 @@ SECRET_END_ARY=()
 USERNAME_END_ARY=()
 TAG=""
 COUNTER=1
-green " ========================================================================="
-green " 简介：tg电报代理脚本"
-green " 系统：debian10"
-green " Youtube：米月"
-green " 电报群：https://t.me/mi_yue"
-green " Youtube频道地址：https://t.im/n21o"
-green " 20200304v3"
-green " ========================================================================="
+green " ========================================================================"
+  green " 简介：tg代理一键脚本"
+  green " 系统：>=debian9"
+  green " Youtube：米月"
+  green " 电报群：https://t.me/mi_yue"
+  green " Youtube频道地址：https://t.im/n21o"
+  green " 版本：20200304v1"
+  green " ========================================================================"
+echo ""
+#read -r -p "Select a port to proxy listen on it (-1 to randomize): " -e -i "443" PORT
 PORT=9443
-
-
+if [[ $PORT -eq -1 ]]; then
+	GetRandomPort
+	echo "I've selected $PORT as your port."
+fi
+#Lets check if the PORT is valid
+if ! [[ $PORT =~ $regex ]]; then
+	echo "$(tput setaf 1)Error:$(tput sgr 0) The input is not a valid number"
+	exit 1
+fi
+if [ "$PORT" -gt 65535 ]; then
+	echo "$(tput setaf 1)Error:$(tput sgr 0): Number must be less than 65536"
+	exit 1
+fi
 #Now the username and secrets
+declare -A limits
+echo "$(tput setaf 3)Warning!$(tput sgr 0) Do not use special characters like \" , ' , $ or... for username"
 while true; do
-    USERNAME=miyue
+	echo "Now tell me a user name. Usernames are used to name secrets: "
+	#read -r -e -i "MTSecret$COUNTER" USERNAME
+    USERNAME=miyue1
+	echo "Do you want to set secret manually or shall I create a random secret?"
+	echo "   1) Manually enter a secret"
+	echo "   2) Create a random secret"
+	#read -r -p "Please select one [1-2]: " -e -i 2 OPTION
     OPTION=2
 	case $OPTION in
 	1)
@@ -595,7 +615,7 @@ while true; do
 	SECRETTEMP+='"'
 	SECRETS+="$SECRETTEMP , "
 	#Setup limiter
-
+	#read -r -p "Do you want to limit users connected to this secret?(y/n) " -e -i "n" OPTION
     OPTION=n
 	OPTION="$(echo $OPTION | tr '[A-Z]' '[a-z]')"
 	case $OPTION in
@@ -616,7 +636,7 @@ while true; do
 		exit 1
 		;;
 	esac
-
+	#read -r -p "Do you want to add another secret?(y/n) " -e -i "n" OPTION
     OPTION=n
 	OPTION="$(echo $OPTION | tr '[A-Z]' '[a-z]')"
 	case $OPTION in
@@ -632,19 +652,71 @@ while true; do
 	esac
 	COUNTER=$((COUNTER + 1))
 done
-
+SECRETS=${SECRETS::${#SECRETS}-2}
 if [ ${#limits[@]} -gt 0 ]; then
 	GenerateConnectionLimiterConfig
 fi
+#Set secure mode
+echo
+echo "1) No Restrictions"
+echo '2) "dd" secrets and TLS connections'
+echo "3) TLS connection only"
+#read -r -p "Do want to restrict the connections? Select one: " -e -i "3" OPTION
+OPTION=3
+case $OPTION in
+'1') 
+	SECURE_MODE="MODES = { \"classic\": True, \"secure\": True, \"tls\": True }"
+	;;
+'2')
+	SECURE_MODE="MODES = { \"classic\": False, \"secure\": True, \"tls\": True }"
+	;;
+'3')
+	SECURE_MODE="MODES = { \"classic\": False, \"secure\": False, \"tls\": True }"
+	;;
+*)
+	echo "$(tput setaf 1)Invalid option$(tput sgr 0)"
+	exit 1
+	;;
+esac
+#Now setup the tag
+#read -r -p "Do you want to setup the advertising tag?(y/n) " -e -i "n" OPTION
+OPTION=n
+OPTION="$(echo $OPTION | tr '[A-Z]' '[a-z]')"
+case $OPTION in
+'y')
+	echo "$(tput setaf 1)Note:$(tput sgr 0) Joined users and admins won't see the channel at very top."
+	echo "On telegram, go to @MTProxybot Bot and enter this server's IP and $PORT as port. Then as secret enter $SECRET"
+	echo "Bot will give you a string named TAG. Enter it here:"
+	read -r TAG
+	;;
+'n') ;;
 
-SECRET="$(hexdump -vn "16" -e ' /1 "%02x"' /dev/urandom)"
-echo "$(tput setaf 3)Warning!$(tput sgr 0) Do not use special characters like \" , ' , $ or... for username"
-
-SECURE_MODE="MODES = { \"classic\": False, \"secure\": False, \"tls\": True }"
-
-if [[ $distro =~ "Debian" ]]; then
+*)
+	echo "$(tput setaf 1)Invalid option$(tput sgr 0)"
+	exit 1
+	;;
+esac
+#Change host mask
+#read -r -p "Select a host that DPI thinks you are visiting (TLS_DOMAIN): " -e -i "www.cloudflare.com" TLS_DOMAIN
+TLS_DOMAIN="www.baidu.com"
+#Now lets install
+#read -n 1 -s -r -p "Press any key to install..."
+clear
+if [[ $distro =~ "CentOS" ]]; then
+	yum -y install epel-release
+	yum -y update
+	yum -y install sed git python36 curl ca-certificates jq
+elif [[ $distro =~ "Ubuntu" ]]; then
+	apt update
+	if ! [[ $(lsb_release -r -s) =~ "17" ]] && ! [[ $(lsb_release -r -s) =~ "18" ]] && ! [[ $(lsb_release -r -s) =~ "19" ]]; then
+		apt-get -y install software-properties-common python-software-properties
+		add-apt-repository ppa:deadsnakes/ppa
+	fi
 	apt-get update
-	apt-get install -y jq ca-certificates iptables-persistent iptables git sed curl wget
+	apt-get -y install python3.6 python3.6-distutils sed git curl jq ca-certificates
+elif [[ $distro =~ "Debian" ]]; then
+	apt-get update
+	apt-get install -y --no-install-recommends --no-install-suggests jq ca-certificates iptables-persistent iptables git sed curl wget
 	if ! command -v "python3.6" >/dev/null; then
 		apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev #python packages
 		#Download and install python 3.6.9
@@ -652,7 +724,12 @@ if [[ $distro =~ "Debian" ]]; then
 		curl -o Python-3.6.9.tar.xz https://www.python.org/ftp/python/3.6.9/Python-3.6.9.tar.xz
 		tar xvf Python-3.6.9.tar.xz
 		cd Python-3.6.9 || exit 2
-		./configure
+		read -r -p "$(tput setaf 4)Question:$(tput sgr 0) Do you want to enable optimizations while building python? If yes, building will take much longer but the python will be faster. (y/n): " -e -i "y" OPTION
+		if [[ $OPTION == "y" || $OPTION == "Y" ]]; then
+			./configure --enable-optimizations
+		else
+			./configure
+		fi
 		make
 		make altinstall
 		ln -s /usr/local/bin/python3.6 /usr/bin/python3.6
@@ -685,7 +762,7 @@ chmod 0777 config.py
 echo "PORT = $PORT
 USERS = { $SECRETS }
 USER_MAX_TCP_CONNS = { $LIMITER_CONFIG }
-TLS_DOMAIN = \"www.baidu.com\"
+TLS_DOMAIN = \"$TLS_DOMAIN\"
 " >>config.py
 if [ -n "$TAG" ]; then
 	TAGTEMP="AD_TAG = "
@@ -698,7 +775,44 @@ echo "$SECURE_MODE" >> config.py
 echo -e "$LIMITER_FILE" >> "limits_bash.txt"
 echo "{}" >> "limits_date.json"
 echo "{}" >> "limits_quota.json"
-
+#Setup firewall
+echo "Setting firewalld rules"
+if [[ $distro =~ "CentOS" ]]; then
+	SETFIREWALL=true
+	if ! yum -q list installed firewalld &>/dev/null; then
+		echo ""
+		read -r -p 'Looks like "firewalld" is not installed Do you want to install it?(y/n) ' -e -i "y" OPTION
+		case $OPTION in
+		"y")
+			yum -y install firewalld
+			systemctl enable firewalld
+			;;
+		*)
+			SETFIREWALL=false
+			;;
+		esac
+	fi
+	if [ "$SETFIREWALL" = true ]; then
+		systemctl start firewalld
+		firewall-cmd --zone=public --add-port="$PORT"/tcp
+		firewall-cmd --runtime-to-permanent
+	fi
+elif [[ $distro =~ "Ubuntu" ]]; then
+	if dpkg --get-selections | grep -q "^ufw[[:space:]]*install$" >/dev/null; then
+		ufw allow "$PORT"/tcp
+	else
+		echo
+		read -r -p 'Looks like "UFW"(Firewall) is not installed Do you want to install it?(y/n) ' -e -i "y" OPTION
+		case $OPTION in
+		"y" | "Y")
+			apt-get install ufw
+			ufw enable
+			ufw allow ssh
+			ufw allow "$PORT"/tcp
+			;;
+		esac
+	fi
+fi
 #Now lets create the service
 cd /etc/systemd/system || exit 2
 touch mtprotoproxy.service
@@ -729,8 +843,10 @@ if [ $CURL_EXIT_STATUS -ne 0 ]; then
 	PUBLIC_IP="YOUR_IP"
 fi
 COUNTER=0
+green " ========================以下tg代理链接==================================="
 for i in "${SECRET_END_ARY[@]}"; do
 	s=$(python3.6 -c "print(\"ee\" + \"$SECRET\" + \"$TLS_DOMAIN\".encode().hex())")
 	echo "${USERNAME_END_ARY[$COUNTER]}: tg://proxy?server=$PUBLIC_IP&port=$PORT&secret=$s"
 	COUNTER=$COUNTER+1
 done
+green " =========================以下tg代理链接==================================="
