Update tg_pxy

diff --git a/tg_pxy b/tg_pxy
--- a/tg_pxy
+++ b/tg_pxy
@@ -176,7 +176,7 @@ if [ -d "/opt/mtprotoproxy" ]; then
 		echo "  9 ) Generate firewall rules"
 		echo "  10) Uninstall Proxy" 
 		echo "  * ) Exit"
-        echo "  * 20200304v1"
+        echo "  * 20200304v2"
 		read -r -p "Please enter a number: " OPTION
 	fi
 	case $OPTION in
@@ -556,14 +556,82 @@ green " 系统：debian10"
 green " Youtube：米月"
 green " 电报群：https://t.me/mi_yue"
 green " Youtube频道地址：https://t.im/n21o"
-green " 20200304"
+green " 20200304v2"
 green " ========================================================================="
 PORT=9443
 
 
 #Now the username and secrets
-declare -A limits
-USERNAME=miyue
+while true; do
+    USERNAME=miyue
+    OPTION=2
+	case $OPTION in
+	1)
+		echo "Enter a 32 character string filled by 0-9 and a-f(hexadecimal): "
+		read -r SECRET
+		#Validate length
+		SECRET="$(echo $SECRET | tr '[A-Z]' '[a-z]')"
+		if ! [[ $SECRET =~ ^[0-9a-f]{32}$ ]]; then
+			echo "$(tput setaf 1)Error:$(tput sgr 0) Enter hexadecimal characters and secret must be 32 characters."
+			exit 1
+		fi
+		;;
+	2)
+		SECRET="$(hexdump -vn "16" -e ' /1 "%02x"' /dev/urandom)"
+		echo "OK I created one: $SECRET"
+		;;
+	*)
+		echo "$(tput setaf 1)Invalid option$(tput sgr 0)"
+		exit 1
+		;;
+	esac
+	SECRET_END_ARY+=("$SECRET")
+	USERNAME_END_ARY+=("$USERNAME")
+	#Now add them to secrets
+	SECRETTEMP='"'
+	SECRETTEMP+="$USERNAME"
+	SECRETTEMP+='":"'
+	SECRETTEMP+="$SECRET"
+	SECRETTEMP+='"'
+	SECRETS+="$SECRETTEMP , "
+	#Setup limiter
+
+    OPTION=n
+	OPTION="$(echo $OPTION | tr '[A-Z]' '[a-z]')"
+	case $OPTION in
+	'y')
+		read -r -p "How many users do you want to connect to this secret? " OPTION
+		if ! [[ $OPTION =~ $regex ]]; then
+			echo "$(tput setaf 1)Error:$(tput sgr 0) The input is not a valid number"
+			exit 1
+		fi
+		#Multiply number of connections by 8. You can manualy change this. Read more: https://github.com/alexbers/mtprotoproxy/blob/master/mtprotoproxy.py#L202
+		OPTION=$((OPTION * 8))
+		limits+=(["$USERNAME"]="$OPTION")
+		;;
+	'n') ;;
+
+	*)
+		echo "$(tput setaf 1)Invalid option$(tput sgr 0)"
+		exit 1
+		;;
+	esac
+
+    OPTION=n
+	OPTION="$(echo $OPTION | tr '[A-Z]' '[a-z]')"
+	case $OPTION in
+	'y') ;;
+
+	'n')
+		break
+		;;
+	*)
+		echo "$(tput setaf 1)Invalid option$(tput sgr 0)"
+		exit 1
+		;;
+	esac
+	COUNTER=$((COUNTER + 1))
+done
 
 if [ ${#limits[@]} -gt 0 ]; then
 	GenerateConnectionLimiterConfig
